// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAycFg2EBYUMlN74qZNPqS9AJYI5sKA_AE',
    appId: '1:316444264839:web:d43ba379c177dc746a2b22',
    messagingSenderId: '316444264839',
    projectId: 'carkett-39e49',
    authDomain: 'carkett-39e49.firebaseapp.com',
    storageBucket: 'carkett-39e49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPK6ktzd170vlQVPKONuvWhnmQqJX9urA',
    appId: '1:316444264839:android:1918082fc34aa0df6a2b22',
    messagingSenderId: '316444264839',
    projectId: 'carkett-39e49',
    storageBucket: 'carkett-39e49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD-1HZw80iWqEy6HTRxe5xd8Oz1Nub75g',
    appId: '1:316444264839:ios:8bd2e9e387e570fe6a2b22',
    messagingSenderId: '316444264839',
    projectId: 'carkett-39e49',
    storageBucket: 'carkett-39e49.appspot.com',
    iosBundleId: 'com.ancikle.carkett',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD-1HZw80iWqEy6HTRxe5xd8Oz1Nub75g',
    appId: '1:316444264839:ios:8bd2e9e387e570fe6a2b22',
    messagingSenderId: '316444264839',
    projectId: 'carkett-39e49',
    storageBucket: 'carkett-39e49.appspot.com',
    iosBundleId: 'com.ancikle.carkett',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAycFg2EBYUMlN74qZNPqS9AJYI5sKA_AE',
    appId: '1:316444264839:web:b84f1343a5cca4556a2b22',
    messagingSenderId: '316444264839',
    projectId: 'carkett-39e49',
    authDomain: 'carkett-39e49.firebaseapp.com',
    storageBucket: 'carkett-39e49.appspot.com',
  );
}
