// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjeWySlrnQssrGZZxWb6ZACV642GBiZPU',
    appId: '1:1001155650177:web:cccc0efb23740dd27b6380',
    messagingSenderId: '1001155650177',
    projectId: 'pilonesdeoriente-386b6',
    authDomain: 'pilonesdeoriente-386b6.firebaseapp.com',
    databaseURL: 'https://pilonesdeoriente-386b6-default-rtdb.firebaseio.com',
    storageBucket: 'pilonesdeoriente-386b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAar1275IrVvchTOSqvO9Q5Rrln5u1tY1c',
    appId: '1:1001155650177:android:257b04a586192ccc7b6380',
    messagingSenderId: '1001155650177',
    projectId: 'pilonesdeoriente-386b6',
    databaseURL: 'https://pilonesdeoriente-386b6-default-rtdb.firebaseio.com',
    storageBucket: 'pilonesdeoriente-386b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7fdTQIoqEIa1eR49JtTzqYVkUATSjgqw',
    appId: '1:1001155650177:ios:56e6ba224620fcc77b6380',
    messagingSenderId: '1001155650177',
    projectId: 'pilonesdeoriente-386b6',
    databaseURL: 'https://pilonesdeoriente-386b6-default-rtdb.firebaseio.com',
    storageBucket: 'pilonesdeoriente-386b6.firebasestorage.app',
    iosBundleId: 'com.example.pilonesDeOriente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7fdTQIoqEIa1eR49JtTzqYVkUATSjgqw',
    appId: '1:1001155650177:ios:56e6ba224620fcc77b6380',
    messagingSenderId: '1001155650177',
    projectId: 'pilonesdeoriente-386b6',
    databaseURL: 'https://pilonesdeoriente-386b6-default-rtdb.firebaseio.com',
    storageBucket: 'pilonesdeoriente-386b6.firebasestorage.app',
    iosBundleId: 'com.example.pilonesDeOriente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjeWySlrnQssrGZZxWb6ZACV642GBiZPU',
    appId: '1:1001155650177:web:8e70ba8f343e85f77b6380',
    messagingSenderId: '1001155650177',
    projectId: 'pilonesdeoriente-386b6',
    authDomain: 'pilonesdeoriente-386b6.firebaseapp.com',
    databaseURL: 'https://pilonesdeoriente-386b6-default-rtdb.firebaseio.com',
    storageBucket: 'pilonesdeoriente-386b6.firebasestorage.app',
  );

}